const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const percent=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'—';
const number=n=>Number(n||0).toLocaleString('zh-CN');
let api='https://exusiai.zzt.si',catalog=[],data=null,page=new URL(location.href).searchParams.get('page')||'cards',sort='offered',direction=-1,lastQuery='',initialModFilters=true;
let deleteToken=/^#delete=([a-f0-9]{64})$/.exec(location.hash)?.[1];
if(deleteToken){history.replaceState(null,'',location.pathname+'?page=privacy');page='privacy';}
if(!['cards','relics','ancients','privacy'].includes(page)) page='cards';
for(const nav of document.querySelectorAll('nav a')) if(nav.dataset.page===page) nav.setAttribute('aria-current','page');
$('#statistics').hidden=page==='privacy';$('#privacy').hidden=page!=='privacy';$('#act').hidden=page!=='cards';
$('#entity-title').textContent=({cards:'卡牌表现',relics:'角色遗物',ancients:'先古遗物'})[page]||'';
if(page!=='cards') $('#metric-note').textContent='仅统计本 Mod 遗物；永久持有率排除中转副本。获得样本由逐层选择、购买与永久栏记录按ID/层数去重，先古选项按游戏记录匹配。';
for(let i=0;i<=10;i++) $('#filters [name=ascension]').add(new Option(`A${i}`,String(i)));
const params=new URL(location.href).searchParams;
for(const name of ['party','mode','abandoned','from','to','ascension']) if(params.has(name)) $('#filters').elements[name].value=params.get(name);
for(const name of ['version','revision']) if(params.get(name)) { const select=$('#filters').elements[name]; select.add(new Option(params.get(name),params.get(name))); select.value=params.get(name); }
function query(){const f=new FormData($('#filters')),p=new URLSearchParams();for(const [key,value] of f)if(value)p.append(key,value);if(initialModFilters)for(const id of params.getAll('exclude'))p.append('exclude',id);return p.toString();}
function enrich(item,act=0){const m=data?.entities?.find(m=>m.id===item.id&&m.act===act)||{},o=data?.overview||{};return {...item,...m,offered:m.offered||0,picked:m.picked||0,owned:m.owned||0,owned_wins:m.owned_wins||0,picked_runs:m.picked_runs||0,picked_wins:m.picked_wins||0,obtained:m.obtained||0,upgraded:m.upgraded||0,removed:m.removed||0,pick_rate:m.offered?m.picked/m.offered:-1,win_rate:act?(m.picked_runs?m.picked_wins/m.picked_runs:-1):(m.owned?m.owned_wins/m.owned:-1),own_rate:o.runs?m.owned/o.runs:-1,average_floor:m.obtained?m.floor_sum/m.obtained:-1};}
function listing(){const act=Number($('#act').value),kind=({cards:'card',relics:'relic',ancients:'ancient'})[page],search=$('#search').value.trim().toLowerCase();return catalog.filter(c=>c.kind===kind&&(!search||`${c.name} ${c.en} ${c.id}`.toLowerCase().includes(search))).map(c=>enrich(c,act)).sort((a,b)=>direction*(typeof a[sort]==='string'?a[sort].localeCompare(b[sort],'zh-CN'):(a[sort]??0)-(b[sort]??0))||a.id.localeCompare(b.id));}
function render(){if(!data)return;const o=data.overview;$('#run-count').textContent=number(o.runs);$('#win-rate').textContent=percent(o.wins,o.runs);$('#wins').textContent=`${number(o.wins)} / ${number(o.runs)} 局通关`;$('#average-floor').textContent=o.runs?Number(o.average_floor).toFixed(1):'—';$('#abandoned-count').textContent=`纳入 ${number(o.abandoned)} 局放弃`;
  const act=page==='cards'?Number($('#act').value):0;
  const cols=act?[['name','卡牌'],['offered','提供次数'],['pick_rate',`第${act}幕选取率`],['win_rate',`第${act}幕选择后通关率`]]: [['name',page==='cards'?'卡牌':'遗物'],['offered','提供次数'],['pick_rate','奖励选择率'],['own_rate','持有率'],['win_rate','持有胜率'],['obtained','获得样本'],['average_floor','平均获得层数'],...(page==='cards'?[['upgraded','升级'],['removed','删除']]:[])];
  $('#table-head').innerHTML=`<tr>${cols.map(([key,name])=>`<th scope="col"><button data-sort="${key}">${name}${sort===key?(direction===1?' ↑':' ↓'):''}</button></th>`).join('')}</tr>`;
  const list=listing();$('#empty').hidden=o.runs>0;$('#rows').innerHTML=list.map(m=>`<tr>${cols.map(([key])=>{
    if(key==='name')return `<td><button class="entity-link" data-id="${esc(m.id)}">${m.art?`<img src="./${esc(m.art)}" alt="" loading="lazy">`:''}<span>${esc(m.name)}<small>${esc(m.en)}</small></span></button></td>`;
    if(key==='pick_rate')return `<td>${percent(m.picked,m.offered)}<span class="sample">${number(m.picked)} / ${number(m.offered)}</span></td>`;
    if(key==='own_rate')return `<td>${percent(m.owned,o.runs)}<span class="sample">${number(m.owned)} / ${number(o.runs)}</span></td>`;
    if(key==='win_rate'){const n=act?m.picked_wins:m.owned_wins,d=act?m.picked_runs:m.owned;return `<td class="${d<30?'low':''}">${percent(n,d)}<span class="sample">${number(n)} / ${number(d)}${d>0&&d<30?' · 低样本':''}</span></td>`;}
    if(key==='average_floor')return `<td>${m.obtained?m.average_floor.toFixed(1):'—'}</td>`;
    return `<td>${number(m[key])}</td>`;
  }).join('')}</tr>`).join('');
  if(page==='cards')$('#metric-note').textContent=act?`第${act}幕选取率按提供次数计算；“选择后通关率”按在该幕选择过该牌的玩家局计算，同局同幕重复选择只计一次。`:'奖励选取率分母为提供次数；持有胜率表示局终卡组持有此牌的玩家局通关率。低于30局标记低样本，相关性不等于因果。';
}
function optionList(name,values){const select=$(`#filters [name=${name}]`),value=select.value||params.get(name)||'';select.innerHTML='<option value="">全部</option>';for(const v of [...new Set(values)])select.add(new Option(v,v));if(value&&!values.includes(value))select.add(new Option(value,value));select.value=value;}
function modList(){const selected=new Set([...$('#mod-list').querySelectorAll('input:checked')].map(x=>x.value));for(const id of params.getAll('exclude'))selected.add(id);initialModFilters=false;params.delete('exclude');$('#mod-list').innerHTML=[...new Set([...data.mods.map(m=>m.id),...selected])].map(id=>`<label><input type="checkbox" name="exclude" value="${esc(id)}" ${selected.has(id)?'checked':''}>${esc(id)}</label>`).join('');$('#exclude-count').textContent=selected.size?`(${selected.size}项)`:'';}
function timestamp(){return new Date(data.updated_at).toLocaleString('zh-CN');}
async function load(){const q=query(),parsed=new URLSearchParams(q);if(parsed.getAll('exclude').length>10){$('#status').textContent='最多排除10项 Mod。';return;}if(parsed.get('from')&&parsed.get('to')&&parsed.get('from')>parsed.get('to')){$('#status').textContent='开始日期不能晚于结束日期。';return;}lastQuery=q;$('#refresh').disabled=true;$('#status').textContent='正在更新社区统计…';
  try{const response=await fetch(api+'/api/stats?'+q,{cache:'no-store'});if(!response.ok)throw new Error();const result=await response.json();if(result.schema!=='exusiai.statistics.v1')throw new Error();if(lastQuery!==q)return;data=result;try{localStorage.setItem('exusiai.snapshot',JSON.stringify({q,data}));}catch{}$('#status').textContent=`${data.stale?'服务暂不可用，显示最近统计 · ':''}更新于 ${timestamp()} · 约15分钟刷新`;
  }catch{let saved;try{saved=JSON.parse(localStorage.getItem('exusiai.snapshot'));}catch{}if(saved?.q===q){data=saved.data;$('#status').textContent=`暂时无法连接，显示本机缓存 · ${timestamp()}`;}else{data=null;$('#status').textContent='统计暂不可用，稍后重试。当前没有此筛选范围的缓存。';$('#rows').replaceChildren();for(const id of ['run-count','win-rate','average-floor'])$('#'+id).textContent='—';$('#empty').hidden=true;}}
  finally{$('#refresh').disabled=false;}
  if(data){optionList('version',data.versions.map(v=>v.version));optionList('revision',data.versions.map(v=>v.revision));modList();const known=new Set([...$('#act').options].map(o=>o.value));for(const act of [...new Set(data.entities.map(e=>e.act))].filter(a=>a>0).sort((a,b)=>a-b))if(!known.has(String(act)))$('#act').add(new Option(`第${act}幕`,String(act)));render();}
}
$('#filters').addEventListener('submit',e=>{e.preventDefault();const q=query();history.replaceState(null,'',location.pathname+'?page='+page+'&'+q);void load();});
$('#filters').addEventListener('reset',()=>{params.delete('exclude');setTimeout(()=>{for(const x of $('#mod-list').querySelectorAll('input'))x.checked=false;void load();},0);});
$('#refresh').onclick=()=>void load();$('#search').oninput=render;$('#act').onchange=render;
$('#mod-search').oninput=()=>{for(const l of $('#mod-list').children)l.hidden=!l.textContent.toLowerCase().includes($('#mod-search').value.toLowerCase());};
$('#table-head').onclick=e=>{const button=e.target.closest('[data-sort]');if(!button)return;if(sort===button.dataset.sort)direction*=-1;else{sort=button.dataset.sort;direction=sort==='name'?1:-1;}render();};
$('#rows').onclick=e=>{const button=e.target.closest('[data-id]');if(!button)return;const item=catalog.find(c=>c.id===button.dataset.id),m=enrich(item),o=data.overview;
  const metric=(title,value,sample)=>`<div><span>${title}</span><strong>${value}</strong><span>${sample}</span></div>`;
  const acts=data.entities.filter(m=>m.id===item.id&&m.act>0).sort((a,b)=>a.act-b.act);
  $('#detail-content').innerHTML=`<div class="detail-top">${item.art?`<img src="./${esc(item.art)}" alt="">`:''}<div><h2>${esc(item.name)}</h2><p class="muted">${esc(item.en)}<br>${esc(item.id)}</p></div></div><div class="detail-grid">${metric('奖励选取率',percent(m.picked,m.offered),`${number(m.picked)} / ${number(m.offered)} 次`)}${metric('最终持有胜率',percent(m.owned_wins,m.owned),`${number(m.owned_wins)} / ${number(m.owned)} 玩家局`)}${metric('最终持有率',percent(m.owned,o.runs),`${number(m.owned)} / ${number(o.runs)} 玩家局`)}${metric('平均获得层数',m.obtained?m.average_floor.toFixed(1):'—',`${number(m.obtained)} 次获得样本`)}</div>${item.kind==='card'?`<h3>分幕观察</h3>${acts.length?acts.map(a=>`<p class="muted">第${a.act}幕：选取 ${percent(a.picked,a.offered)}（${a.picked}/${a.offered}次）；选择后通关 ${percent(a.picked_wins,a.picked_runs)}（${a.picked_wins}/${a.picked_runs}玩家局）</p>`).join(''):'<p class="muted">无分幕选牌样本</p>'}`:''}<p class="muted">以上沿用当前筛选。暂无分母显示“—”，小样本仅供观察。</p>`;$('#detail').showModal();
};$('#close').onclick=()=>$('#detail').close();
$('#export').onclick=()=>{if(!data)return;const act=page==='cards'?Number($('#act').value):0;const header=['id','name','act','runs','offered','picked','owned','owned_wins','picked_runs','picked_wins','obtained','floor_sum','upgraded','removed'];const rows=listing().map(m=>header.map(k=>k==='runs'?data.overview.runs:k==='act'?act:m[k]??0));const csv=[header,...rows].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));link.download=`exusiai-${page}-act${act}-${new Date(data.updated_at).toISOString().slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
if(deleteToken){$('#delete-panel').hidden=false;$('#delete-confirm').onchange=()=>$('#delete').disabled=!$('#delete-confirm').checked;$('#delete').onclick=async()=>{$('#delete').disabled=true;$('#delete-status').textContent='正在删除…';try{const r=await fetch(api+'/api/delete',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+deleteToken},body:JSON.stringify({confirm:'delete-my-statistics'})});if(!r.ok)throw new Error();const result=await r.json();deleteToken=undefined;$('#delete-status').textContent=`已删除 ${result.runs} 局记录并撤销身份。汇总缓存约15分钟后更新。`;}catch{$('#delete-status').textContent='删除未确认成功，可稍后重试。';$('#delete').disabled=false;}};}
try{const build=await(await fetch('./build.json',{cache:'no-store'})).json();api=build.api;$('#build').textContent=`构建 ${build.build_id || build.commit} · 仅公开聚合数据`;}catch{}
if(page!=='privacy'){try{catalog=await(await fetch('./catalog.json')).json();await load();setInterval(()=>{if(document.visibilityState==='visible')void load();},900000);}catch{$('#status').textContent='站点资源加载失败，请刷新页面。';}}
