import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const stat=fileURLToPath(new URL('../',import.meta.url));
const wrangler=fileURLToPath(new URL('../node_modules/wrangler/bin/wrangler.js',import.meta.url));
const run=args=>execFileSync(process.execPath,[wrangler,...args,'--config','worker/wrangler.jsonc'],{cwd:stat,stdio:'inherit'});
execFileSync(process.execPath,['scripts/build.mjs'],{cwd:stat,stdio:'inherit'});
execFileSync(process.execPath,['node_modules/typescript/bin/tsc','--noEmit'],{cwd:stat,stdio:'inherit'});
execFileSync(process.execPath,['--test',...['worker.test.mjs','web.test.mjs','card-metadata.test.mjs','incremental.test.mjs','publication.test.mjs'].map(n=>'tests/'+n)],{cwd:stat,stdio:'inherit'});
run(['deploy','--dry-run']);
run(['d1','migrations','apply','exusiai-stat','--remote']);
const ready=(await fetch('https://jimmyzzt.github.io/AK_Exusiai/data/manifest.json')).ok;
run(ready?['deploy']:['deploy','--var','STATIC_STATS_READY:false']);
execFileSync('gh',['workflow','run','stat-pages.yml','--repo','Jimmyzzt/AK_Exusiai','--ref','main','-f','bootstrap='+!ready],{stdio:'inherit'});
console.log(ready?'Pages publication submitted.':'Bootstrap submitted; after verifying the first static release, run npm run deploy to retire the cache-only bridge.');
