import {METRICS,metric} from './metrics.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('zh-CN');
const percent=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'—';
const TAGS={character:'Character · 角色',acts:'Acts · 幕数',extend:'Extend · 内容扩展',qol:'QoL',visual:'Visual · 视觉',audio:'Audio · 音频',library:'工具/依赖',misc:'其他',untagged:'无标签'};
const params=new URL(location.href).searchParams;
let page=params.get('page')||'cards';if(!['cards','relics','ancients','privacy'].includes(page))page='cards';
let api='https://exusiai.zzt.si',catalog=[],data=null,view='grid',sort='offered',direction=-1,requestId=0;
const previews=new Map();
const excluded=new Set(params.getAll('exclude').filter(id=>!['AK_Exusiai','STS2-RitsuLib'].includes(id)));
const storage={get(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}},set(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}};
view=storage.get('exusiai.view','grid');if(!['grid','list'].includes(view))view='grid';
let tileKeys=storage.get('exusiai.metrics',['pick','win','pwar']).filter(k=>k in METRICS);if(!tileKeys.length)tileKeys=['pick','win','pwar'];
const kind=({cards:'card',relics:'relic',ancients:'ancient'})[page];
for(const nav of all('nav a'))if(nav.dataset.page===page)nav.setAttribute('aria-current','page');
$('#statistics').hidden=page==='privacy';$('#privacy').hidden=page!=='privacy';$('#entity-title').textContent=({cards:'卡牌表现',relics:'角色遗物',ancients:'先古遗物'})[page]||'';
const form=$('#filters');for(let i=0;i<=10;i++)form.elements.ascension.add(new Option('A'+i,String(i)));
for(const name of ['party','mode','abandoned','from','to','ascension','act','tag_mode'])if(params.has(name))form.elements[name].value=params.get(name);
for(const name of ['version','revision'])if(params.get(name)){form.elements[name].add(new Option(params.get(name),params.get(name)));form.elements[name].value=params.get(name);}
form.elements.split.checked=params.get('split')==='1';
$('#tag-list').innerHTML=Object.entries(TAGS).map(([key,label])=>`<label><input type="checkbox" name="tags" value="${key}" ${params.getAll('tags').includes(key)?'checked':''}>${label}</label>`).join('');
const available=page==='cards'?Object.keys(METRICS):['pick','win','owned','offered','obtained','floor'];
$('#metric-list').innerHTML=available.filter(k=>k!=='offered').map(k=>`<label title="${esc(METRICS[k][1])}"><input type="checkbox" value="${k}" ${tileKeys.includes(k)?'checked':''}>${METRICS[k][0]}</label>`).join('');
if(page!=='cards'){form.elements.split.disabled=true;tileKeys=tileKeys.filter(k=>available.includes(k));if(!tileKeys.length)tileKeys=['pick','win','owned'];}
for(const key of available)$('#sort').add(new Option(METRICS[key][0],key));$('#sort').add(new Option('名称','name'));$('#sort').value=sort;
function query(){const p=new URLSearchParams();for(const [k,v] of new FormData(form))if(v&&k!=='exclude')p.append(k,v);for(const id of [...excluded].sort())p.append('exclude',id);return p;}
function summary(){const tags=all('#tag-list input:checked').map(i=>i.value),white=form.elements.tag_mode.value==='white';$('#exclude-count').textContent=excluded.size||tags.length||white?`· ${num(excluded.size)} 项手动 / ${tags.length} 类标签`:'';$('#scope-summary').textContent=`${form.elements.act.selectedOptions[0]?.textContent||'前三幕'} · ${excluded.size||tags.length||white?'已筛选 Mod 环境':'全部 Mod 组合'}`;
 for(const label of all('#mod-list label')){const tagged=white?!tags.includes(label.dataset.tag):tags.includes(label.dataset.tag);label.classList.toggle('auto-excluded',tagged);label.title=tagged?'该 Mod 已被标签规则排除':'勾选即可手动排除';} }
function modList(){const search=$('#mod-search').value.toLowerCase();$('#mod-list').innerHTML=(data.mods||[]).filter(m=>!['AK_Exusiai','STS2-RitsuLib'].includes(m.id)).map(m=>`<label data-tag="${esc(m.primary_tag)}" ${!`${m.id} ${m.title}`.toLowerCase().includes(search)?'hidden':''}><input type="checkbox" name="exclude" value="${esc(m.id)}" ${excluded.has(m.id)?'checked':''}><span class="mod-name">${esc(m.title||m.id)}${m.title?`<small>${esc(m.id)}</small>`:''}</span><span class="mod-count">${num(m.uses)} 局</span><span class="badge" title="${esc((m.official_tags||[]).join(' · ')||'未匹配到官方标签')}">${esc(TAGS[m.primary_tag]||'无标签')}</span></label>`).join('');summary();}
function row(item,variant=-1,act=0){const meta=catalog.find(c=>c.id===item.id)||item;return {...meta,...data.entities.find(e=>e.id===item.id&&e.variant===variant&&e.act===act),variant,act};}
function title(m){return m.name+(m.variant===1?' +':m.variant===0?' · 基础':'');}
function art(m){return m.art?`./${m.art}?v=${m.art_revision||''}`:'';}
function rules(text){return esc(text).replace(/\[(gold|blue)\]([\s\S]*?)\[\/\1\]/g,(_,color,body)=>`<span class="rule-${color}">${body}</span>`).replace(/\n/g,'<br>');}
function previewKey(m){return m.id+':'+m.variant;}
function previewUp(m){return m.can_upgrade!==false&&(previews.get(previewKey(m))??m.variant===1);}
function rarityClass(m){return 'rarity-'+(m.type==='Curse'?'curse':m.type==='Status'?'token':(m.rarity||'Common').toLowerCase());}
function visual(m){const up=previewUp(m),name=m.name+(up?' +':''),en=m.en+(up?' +':''),description=m.descriptions?.zhs?.[up?1:0]||'',ruleId='rules-'+m.id+'-'+m.variant,type=({Attack:'攻击',Skill:'技能',Power:'能力',Curse:'诅咒',Status:'状态'})[m.type];
 return `<div class="card-visual" data-id="${m.id}" data-variant="${m.variant}" data-up="${up?1:0}"><button class="card-open" aria-label="查看${esc(name)}详情" ${description?`aria-describedby="${ruleId}"`:''}>${m.art?`<img src="${art(m)}" alt="" loading="lazy">`:''}</button><div class="rule-shade"></div>${m.cost?`<span class="card-cost" aria-label="费用 ${esc(m.cost[up?1:0])}">${esc(m.cost[up?1:0])}</span>`:''}${m.kind==='card'&&m.can_upgrade!==false?`<button class="upgrade-toggle" data-preview="${previewKey(m)}" aria-label="${up?'查看基础版':'查看升级版'}：${esc(m.name)}" aria-pressed="${up}" title="切换基础／升级说明；统计沿用当前对局筛选">${up?'+':''}</button>`:''}${description?`<div class="card-description" id="${ruleId}"><div class="card-rule-content" tabindex="0">${rules(description)}</div></div>`:''}<div class="card-caption">${type?`<span class="type-label ${rarityClass(m)}">${type}</span>`:''}<div class="name-row"><span class="name-zh">${esc(name)}</span><span class="name-en" lang="en">${esc(en)}</span></div></div></div>`;
}
function listing(){const search=$('#search').value.toLowerCase().trim(),split=data.filters.split&&page==='cards';return catalog.filter(c=>c.kind===kind&&(!search||`${c.name} ${c.en} ${c.id}`.toLowerCase().includes(search))).flatMap(c=>split?[row(c,0),row(c,1)]:[row(c)]).sort((a,b)=>{const av=sort==='name'?title(a):metric(sort,a,data.overview).value,bv=sort==='name'?title(b):metric(sort,b,data.overview).value;if(av==null&&bv!=null)return 1;if(bv==null&&av!=null)return -1;return (sort==='name'?String(av).localeCompare(String(bv),'zh-CN')*direction:((av??0)-(bv??0))*direction)||a.id.localeCompare(b.id)||a.variant-b.variant;});}
function label(key,prefix=''){return `<span class="metric-label" title="${esc(METRICS[key][1])}" tabindex="0">${prefix}${esc(METRICS[key][0])}</span>`;}
function value(key,m){const v=metric(key,m,data.overview),inverse=key==='delta_hp'||key==='delta_turns',color=v.signed&&v.value?(v.value*(inverse?-1:1)>0?'positive':'negative'):'';return `<strong class="metric-value ${color}">${v.text}</strong><small class="sample">${v.value==null?(v.samples?'覆盖不足':'暂无样本'):`${num(v.samples)} ${['pick','offered','war','pwar','pwar_rate','delta_pick','delta_war'].includes(key)?'次':'样本'}${v.low?' · 小样本':''}`}</small>`;}
function columns(){let cols=[['name',0],...available.map(k=>[k,0])];if(page==='cards'){const acts=['1','2','3'].includes(data.filters.act)?[+data.filters.act]:data.filters.act==='all'?[...new Set(data.entities.filter(e=>e.act>0).map(e=>e.act))].sort((a,b)=>a-b):[1,2,3];for(const act of acts)for(const key of ['pick','war','pwar'])cols.push([key,act]);}return cols;}
function render(){if(!data)return;const o=data.overview;$('#run-count').textContent=num(o.runs);$('#win-rate').textContent=percent(o.wins,o.win_samples);$('#wins').textContent=`${num(o.wins)} / ${num(o.win_samples)} 局通关${o.win_samples<o.runs?' · 部分旧局结果未知':''}`;$('#average-floor').textContent=o.floor_samples?Number(o.average_floor).toFixed(1):'—';$('#abandoned-count').textContent=`纳入 ${num(o.abandoned)} 局放弃 · ${num(o.floor_samples)} 局层数样本`;$('#coverage').textContent=`${num(o.detailed_runs)} 局支持完整指标`;const list=listing();$('#result-count').textContent=`${num(list.length)} 项内容`;$('#empty').hidden=o.runs>0;$('#search-empty').hidden=list.length>0;$('#tiles').hidden=view!=='grid';$('#table-wrap').hidden=view!=='list';$('#view-grid').setAttribute('aria-pressed',String(view==='grid'));$('#view-list').setAttribute('aria-pressed',String(view==='list'));
 if(view==='grid')$('#tiles').innerHTML=list.map(m=>`<article class="tile ${m.kind}" data-slot="${previewKey(m)}">${visual(m)}<div class="tile-metrics">${tileKeys.map(k=>`<div>${label(k)}${value(k,m)}</div>`).join('')}</div></article>`).join('');
 else{const cols=columns();$('#table-head').innerHTML=`<tr>${cols.map(([k,a])=>`<th><button data-sort="${k}" ${a?'disabled':''}>${k==='name'?'名称':label(k,a?`幕${a} · `:'')}${sort===k&&!a?(direction<0?' ↓':' ↑'):''}</button></th>`).join('')}</tr>`;$('#rows').innerHTML=list.map(m=>`<tr>${cols.map(([k,a])=>k==='name'?`<td><button class="entity-link" data-id="${m.id}" data-variant="${m.variant}">${m.art?`<img src="${art(m)}" alt="" loading="lazy">`:''}<span>${esc(title(m))}<small>${esc(m.en)}</small></span></button></td>`:`<td>${value(k,a?row(m,m.variant,a):m)}</td>`).join('')}</tr>`).join('');}summary();}
function options(name,values){const select=form.elements[name],current=select.value;select.innerHTML='<option value="">全部</option>';for(const v of [...new Set([...values,current])].filter(Boolean))select.add(new Option(v,v));select.value=current;}
async function load(){const p=query(),q=p.toString(),id=++requestId;if(p.get('from')&&p.get('to')&&p.get('from')>p.get('to')){$('#status').textContent='开始日期不能晚于结束日期。';return;}$('#refresh').disabled=true;$('#status').textContent='正在更新社区统计…';
 try{const response=await fetch(api+'/api/stats'+(q.length<=6000?'?'+q:''),q.length<=6000?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q}),cache:'no-store'});if(!response.ok)throw new Error('unavailable');const result=await response.json();if(result.schema!=='exusiai.statistics.v1')throw new Error('schema');if(id!==requestId)return;data=result;storage.set('exusiai.snapshot',{q,data});$('#status').textContent=`${data.stale?'暂不可用，显示最近统计 · ':''}更新于 ${new Date(data.updated_at).toLocaleString('zh-CN')} · 约15分钟刷新`;
 }catch{if(id!==requestId)return;const saved=storage.get('exusiai.snapshot',null);if(saved?.q===q){data=saved.data;$('#status').textContent=`显示本机缓存 · ${new Date(data.updated_at).toLocaleString('zh-CN')}`;}else{data=null;$('#status').textContent='统计暂不可用，稍后重试。';$('#tiles').replaceChildren();$('#rows').replaceChildren();for(const key of ['run-count','win-rate','average-floor'])$('#'+key).textContent='—';}}finally{if(id===requestId)$('#refresh').disabled=false;}
 if(data){options('version',data.versions.map(v=>v.version));options('revision',data.versions.map(v=>v.revision));modList();render();}}
function apply(){const p=query();p.set('page',page);history.replaceState(null,'',location.pathname+'?'+p);void load();}
form.onsubmit=e=>{e.preventDefault();apply();};form.onreset=()=>setTimeout(()=>{excluded.clear();form.elements.tag_mode.value='black';for(const input of all('#tag-list input'))input.checked=false;apply();},0);
$('#open-mods').onclick=()=>$('#mods').showModal();$('#close-mods').onclick=()=>$('#mods').close();$('#apply-mods').onclick=()=>{$('#mods').close();apply();};$('#clear-mods').onclick=()=>{excluded.clear();form.elements.tag_mode.value='black';for(const input of all('#tag-list input'))input.checked=false;modList();};
$('#mod-list').onchange=e=>{const i=e.target;if(i.checked)excluded.add(i.value);else excluded.delete(i.value);summary();};$('#mod-search').oninput=modList;$('#tag-list').onchange=summary;form.elements.tag_mode.onchange=summary;
$('#metric-list').onchange=()=>{tileKeys=all('#metric-list input:checked').map(i=>i.value);if(!tileKeys.length){tileKeys=[page==='cards'?'pick':'win'];$('#metric-list input[value="'+tileKeys[0]+'"]').checked=true;}storage.set('exusiai.metrics',tileKeys);render();};
$('#view-grid').onclick=()=>{view='grid';storage.set('exusiai.view',view);render();};$('#view-list').onclick=()=>{view='list';storage.set('exusiai.view',view);render();};$('#sort').onchange=()=>{sort=$('#sort').value;direction=sort==='name'?1:-1;render();};$('#search').oninput=render;$('#refresh').onclick=()=>void load();
$('#table-head').onclick=e=>{const b=e.target.closest('[data-sort]');if(!b||b.disabled)return;if(sort===b.dataset.sort)direction*=-1;else{sort=b.dataset.sort;direction=sort==='name'?1:-1;}$('#sort').value=sort;render();};
let openedDetail=null,detailUpgraded=false;
function renderDetail(){
 const m=openedDetail,up=detailUpgraded;
 $('#detail-title').textContent=m.name+(up?' +':'');
 $('#detail-en').textContent=m.en+(up?' +':'');
 const type=({Attack:'攻击',Skill:'技能',Power:'能力',Curse:'诅咒',Status:'状态'})[m.type];
 $('#detail-type').hidden=!type;$('#detail-type').textContent=type||'';$('#detail-type').className='type-label '+rarityClass(m);
 $('#detail-upgrade').hidden=m.kind!=='card'||m.can_upgrade===false;
 $('#detail-upgrade').textContent=up?'+':'';$('#detail-upgrade').setAttribute('aria-pressed',String(up));$('#detail-upgrade').setAttribute('aria-label',(up?'查看基础版':'查看升级版')+'：'+m.name);
 const acts=data.entities.filter(r=>r.id===m.id&&r.variant===m.variant&&r.act>0).sort((a,b)=>a.act-b.act);
 $('#detail-content').innerHTML=`<div class="detail-overview"><figure class="detail-picture">${m.art?`<img class="detail-art${m.kind==='card'?'':' detail-icon'}" src="${art(m)}" alt="">`:''}${m.cost?`<span class="card-cost" aria-label="费用 ${esc(m.cost[up?1:0])}">${esc(m.cost[up?1:0])}</span>`:''}</figure>${m.descriptions?`<div class="detail-rules"><div>${rules(m.descriptions.zhs[up?1:0])}</div></div>`:''}</div><div class="detail-grid">${available.filter(k=>k!=='offered').map(k=>`<div>${label(k)}${value(k,m)}</div>`).join('')}</div>${page==='cards'?`<h3>逐幕表现</h3>${acts.length?acts.map(a=>`<div class="act-row"><strong>第${a.act}幕</strong>${['pick','war','pwar'].map(k=>`<div>${label(k)}${value(k,a)}</div>`).join('')}</div>`).join(''):'<p class="muted">暂无选牌样本</p>'}`:''}`;
}
function detail(e){const b=e.target.closest('[data-id]');if(!b)return;const item=catalog.find(c=>c.id===b.dataset.id);openedDetail=row(item,+b.dataset.variant);detailUpgraded=b.dataset.up!==undefined?b.dataset.up==='1':openedDetail.variant===1;renderDetail();$('#detail').showModal();}
$('#detail-upgrade').onclick=()=>{const scroll=$('#detail').scrollTop;detailUpgraded=!detailUpgraded;renderDetail();$('#detail').scrollTop=scroll;};

$('#tiles').onclick=e=>{const toggle=e.target.closest('[data-preview]');if(!toggle){detail(e);return;}const card=toggle.closest('[data-id]'),m=row(catalog.find(c=>c.id===card.dataset.id),+card.dataset.variant);previews.set(previewKey(m),!previewUp(m));card.outerHTML=visual(m);const next=all('[data-preview]').find(b=>b.dataset.preview===previewKey(m));next?.focus({preventScroll:true});};$('#rows').onclick=detail;$('#close').onclick=()=>$('#detail').close();
$('#export').onclick=()=>{if(!data)return;const cols=columns(),header=cols.map(([k,a])=>k==='name'?'名称':(a?`幕${a} `:'')+METRICS[k][0]);const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';const csv=[header,...listing().map(m=>cols.map(([k,a])=>k==='name'?title(m):metric(k,a?row(m,m.variant,a):m,data.overview).value))].map(r=>r.map(quote).join(',')).join('\r\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));link.download=`exusiai-${page}-${new Date(data.updated_at).toISOString().slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
try{const build=await(await fetch('./build.json',{cache:'no-store'})).json();api=build.api;$('#build').textContent=`构建 ${build.build_id||build.commit} · 仅公开聚合数据`;}catch{}
if(['localhost','127.0.0.1'].includes(location.hostname))api=location.origin;
if(page!=='privacy'){try{catalog=await(await fetch('./catalog.json',{cache:'no-cache'})).json();await load();setInterval(()=>{if(document.visibilityState==='visible')void load();},900000);}catch{$('#status').textContent='站点资源加载失败，请刷新页面。';}}
