<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../local.props" Condition="Exists('../../../local.props')" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework><OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <RitsuLibAutoCopy>false</RitsuLibAutoCopy>
    <GodotProjectDir>$(MSBuildProjectDirectory)/../../../</GodotProjectDir>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="GodotProjectDir" />
    <ProjectReference Include="../../../AK_Exusiai.csproj" />
    <Reference Include="sts2" HintPath="$(Sts2Dir)/data_sts2_windows_x86_64/sts2.dll" />
    <Reference Include="GodotSharp" HintPath="$(Sts2Dir)/data_sts2_windows_x86_64/GodotSharp.dll" />
  </ItemGroup>
</Project>
